[Task][68541] Create section UI
awesome-academy/ios_oe_nghiem_dinh_bach_project_1-Public pull request #7
Opened 2023-09-18 08:05 UTC by bachnd2k1

## [Pull request title]
[Task][68541] Create section UI

### [Redmine link]
https://edu-redmine.sun-asterisk.vn/issues/68541

#### Screenshots (nếu có)

https://github.com/awesome-academy/ios_oe_nghiem_dinh_bach_project_1-Public/assets/75248050/b60e4fd0-fcd4-4d8d-b5b1-6fa5d9d74252

2023-09-18 08:13 UTC, TuanKieuDev commented on MovieApp/MovieApp/Cell/MovieCell.swift
> +class MovieCell: UICollectionViewCell {
final

2023-09-18 08:14 UTC, TuanKieuDev commented on MovieApp/MovieApp/Cell/SectionCell.swift
> +class SectionCell: UITableViewCell {
final

2023-09-18 08:14 UTC, TuanKieuDev commented on MovieApp/MovieApp/Cell/SectionCell.swift
> +extension SectionCell: UICollectionViewDelegate, UICollectionViewDataSource {
Tách ra

2023-09-18 08:14 UTC, TuanKieuDev commented on MovieApp/MovieApp/View/HeaderView.swift
> +class HeaderView: UIView {
final

2023-09-18 08:15 UTC, TuanKieuDev commented
Project này dùng toàn programmatically rồi, không chia XIB

2023-09-18 08:20 UTC, tiennt-0361 commented on MovieApp/MovieApp/Controller/HomeViewController.swift
> +        let image = UIImage(named: "netflix")?.withRenderingMode(.alwaysOriginal)
define

2023-09-18 08:20 UTC, tiennt-0361 commented on MovieApp/MovieApp/Cell/MovieCell.swift
> +    static let identifier = "MovieCell"
define

2023-09-18 08:20 UTC, tiennt-0361 commented on MovieApp/MovieApp/Cell/MovieCell.swift
> +        let url = "https://image.tmdb.org/t/p/w500\(model)"
define

2023-09-18 08:20 UTC, tiennt-0361 commented on MovieApp/MovieApp/Controller/HomeViewController.swift
> +                    cell.configure(with: movies)
cái này mình để khi debug thôi

2023-09-18 08:20 UTC, tiennt-0361 commented on MovieApp/MovieApp/View/HeaderView.swift
> +        button.translatesAutoresizingMaskIntoConstraints = false
define string

2023-09-18 08:20 UTC, tiennt-0361 commented on MovieApp/MovieApp/View/HeaderView.swift
> +        let url = "https://image.tmdb.org/t/p/w500\(posterURL)"
define

2023-09-18 08:42 UTC, tiennt-0361 approved these changes

2023-09-18 08:47 UTC, tunghs-1253 requested changes

2023-09-18 08:47 UTC, tunghs-1253 commented on MovieApp/MovieApp/Cell/MovieCell.swift
> +    public func configure(posterURL: String) {
Cách dòng ra em

2023-09-18 08:47 UTC, tunghs-1253 commented on MovieApp/MovieApp/Cell/MovieCell.swift
> +        }
Retain cycle

2023-09-18 08:47 UTC, tunghs-1253 commented on MovieApp/MovieApp/Cell/SectionCell.swift
> +        }
Đang ở main sẵn rồi, đưa vào làm gì nữa em

2023-09-18 08:47 UTC, tunghs-1253 commented on MovieApp/MovieApp/Controller/HomeViewController.swift
> +        return 1
Xoá

2023-09-18 08:47 UTC, tunghs-1253 commented on MovieApp/MovieApp/Controller/HomeViewController.swift
> +                    print(error.localizedDescription)
check tất cả print và xoá

2023-09-18 08:47 UTC, tunghs-1253 commented on MovieApp/MovieApp/View/HeaderView.swift
> +    private func applyConstraints() {
Dùng xib em

2023-09-18 08:47 UTC, tunghs-1253 commented on MovieApp/MovieApp/View/HeaderView.swift
> +//        let url = "https://image.tmdb.org/t/p/w500\(posterURL)"
Xoá

2023-09-18 09:03 UTC, bachnd2k1 commented on MovieApp/MovieApp/Controller/HomeViewController.swift
> +        return 1
Em tạo 1 tableview trong mỗi section có 1 row chứa 1 collectionview mà anh. Bắt buộc phải define numberOfRowsInSection chứ sao xoá được hả anh. Chỉ xoá được numberOfSections thôi anh ạ.

2023-09-18 09:11 UTC, bachnd2k1 commented on MovieApp/MovieApp/Cell/SectionCell.swift
> +        }
![Screen Shot 2023-09-18 at 16 10 37](https://github.com/awesome-academy/ios_oe_nghiem_dinh_bach_project_1-Public/assets/75248050/6b4a4533-e291-404d-a40b-74b6dc20c35f)

Không làm như vậy bị warning anh ạ

2023-09-18 09:13 UTC, bachnd2k1 commented on MovieApp/MovieApp/View/HeaderView.swift
> +    private func applyConstraints() {
![Screen Shot 2023-09-18 at 16 13 03](https://github.com/awesome-academy/ios_oe_nghiem_dinh_bach_project_1-Public/assets/75248050/e9b0221d-d614-4c8b-8fd0-24226d953155)
Em tạo file xib nhưng không auto layout được anh ạ nên em dùng promatically. Storyboard default thì em autolayout được anh ạ.

2023-09-18 09:18 UTC, tunghs-1253 commented on MovieApp/MovieApp/View/HeaderView.swift
> +    private func applyConstraints() {
Không có chuyện không auto layout được nhé

2023-09-18 09:52 UTC, hlinh88 commented on MovieApp/MovieApp/Controller/HomeViewController.swift
> +                }
Có thể viết ngắn gọn pass loại data cần get thay vì switch case lặp đi lặp lại nhiều dòng code như này

2023-09-18 09:52 UTC, hlinh88 commented on MovieApp/MovieApp/Utils.swift
> +                    return
handle error bằng popup

2023-09-18 09:52 UTC, hlinh88 commented on MovieApp/MovieApp/Utils.swift
> +            print("Invalid URL")
tương tự

2023-09-18 09:52 UTC, hlinh88 commented on MovieApp/MovieApp/View/HeaderView.swift
> +        NSLayoutConstraint.activate(infoButtonConstraints)
dùng xib hoặc storyboard

2023-09-19 05:55 UTC, tunghs-1253 commented on MovieApp/MovieApp/Extension/UIViewController.swift
> +        }
Còn phần này nữa em

2023-09-19 05:55 UTC, tunghs-1253 commented on MovieApp/MovieApp/View/CustomToastView.swift
> +        ])
Vẫn chưa layout bằng autolayout

2023-09-19 10:06 UTC, ghost approved these changes

2023-09-19 10:07 UTC, merged